### PR TITLE
lbwxly'Branch

### PR DESCRIPTION
**Pull request by lbwxly**
1. generate guid primary key with lowercase(useful in my project, you can refuse it)
2. print raw sql string based on the setting
3. add api to commit object without committing embedded object.

### CODE REVIEW

**Comment by editfmah** [comment]
Hi @lbwxly, i'm just reviewing this pull request, I like the functionality, but we are just wondering if we should adapt the interface to not be another overload of commit.  Maybe a property on SRKObject for all object settings?

**Comment by lbwxly** [comment]
yes, the setting approach should be the most scenario. the reason for my current code is： in my project, i only need to skip commit for parts of embed objects, not all. so, is it possible keep both: a property on SRKObject and overload of commit?

**Comment by editfmah** [comment]
Hi @lbwxly, just looking to integrate the "ignore entities" code, I like what you have done. The only thing is I wanted to keep the interface as clean as possible, but the alternative is not too clean either, but it would allow combinations.

We are thinking of having a CommitOptions class, which can be set on any object and then it can be inspected by Shark to see if it needs to do anything different.  So some that immediately come to mind would be:

- ignoreEntities: (array of entities to ignore as per your implementation)
- raiseErrors: BOOL (so transactions always complete, even if syntax errors were encountered)
- triggerEvents: BOOL (to make commits faster if you don't want to use the event model)
- commitChildObjects: BOOL (what many developers may want, although it is quite dangerous)

etc.....

The class would have sensible defaults, so if the developer does not create one and embed it within the object, then the code will operate as expected.

This way, instead of creating more and more method overloads we have a class which can be extended without breaking code.

But this is the way I like to develop things, but I would welcome the feedback from the wider community as to their preference.

and example in use would be:

```
myObject.commitOptions.raiseErrors = false
// then commit as normal
```

Thanks for your contributions, they are very welcome.
Adrian

**Comment by lbwxly** [comment]
@editfmah i agree with you. it is perfect.

**Comment by editfmah** [comment]
@lbwxly okay, cool.  I'll change your implementation to work like that then.

**Comment by lbwxly** [comment]
@editfmah ok, it's great.

**Comment by lbwxly** [comment]
@editfmah so, should I close this pull request?

**Comment by editfmah** [comment]
@lbwxly, i'll close it once i've finished looking through your changes to make sure i've not missed anything.

**Comment by editfmah** [comment]
Okay, i think this has now been completed.

**Pull request closed without merging**
